version: '3'

services:
  web:
    image: michelangelo505/django_test
    working_dir: /app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: test
    ports:
      - "8000:8000"
